### ISSUE TITLE
Needs to be blue

### ISSUE THREAD

**Issue by faizaanshamsi** [greenfieldhq/ember-selectize#1]
- [ ] Make blue

[Blue](https://www.google.com/search?site=&tbm=isch&source=hp&biw=1440&bih=1341&q=blue&oq=blue&gs_l=img.3..0l10.399.660.0.733.4.4.0.0.0.0.126.288.2j1.3.0....0...1ac.1.64.img..1.3.288.uqxiBcdVj1I)

**Comment by HeroicEric** [comment]
go away
